/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef databaseservice_CONSTANTS_H
#define databaseservice_CONSTANTS_H

#include "databaseservice_types.h"

namespace databaseservice {

class databaseserviceConstants {
 public:
  databaseserviceConstants();

};

extern const databaseserviceConstants g_databaseservice_constants;

} // namespace

#endif
