/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProfileService_H
#define ProfileService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "ProfileServiceTypes.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProfileServiceIf {
 public:
  virtual ~ProfileServiceIf() {}
  virtual void getData(GetResult& _return, const std::string& key) = 0;
  virtual bool setData(const std::string& key, const std::string& value) = 0;
  virtual bool removeData(const std::string& key) = 0;
};

class ProfileServiceIfFactory {
 public:
  typedef ProfileServiceIf Handler;

  virtual ~ProfileServiceIfFactory() {}

  virtual ProfileServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProfileServiceIf* /* handler */) = 0;
};

class ProfileServiceIfSingletonFactory : virtual public ProfileServiceIfFactory {
 public:
  ProfileServiceIfSingletonFactory(const boost::shared_ptr<ProfileServiceIf>& iface) : iface_(iface) {}
  virtual ~ProfileServiceIfSingletonFactory() {}

  virtual ProfileServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProfileServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProfileServiceIf> iface_;
};

class ProfileServiceNull : virtual public ProfileServiceIf {
 public:
  virtual ~ProfileServiceNull() {}
  void getData(GetResult& /* _return */, const std::string& /* key */) {
    return;
  }
  bool setData(const std::string& /* key */, const std::string& /* value */) {
    bool _return = false;
    return _return;
  }
  bool removeData(const std::string& /* key */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _ProfileService_getData_args__isset {
  _ProfileService_getData_args__isset() : key(false) {}
  bool key :1;
} _ProfileService_getData_args__isset;

class ProfileService_getData_args {
 public:

  ProfileService_getData_args(const ProfileService_getData_args&);
  ProfileService_getData_args& operator=(const ProfileService_getData_args&);
  ProfileService_getData_args() : key() {
  }

  virtual ~ProfileService_getData_args() throw();
  std::string key;

  _ProfileService_getData_args__isset __isset;

  void __set_key(const std::string& val);

  bool operator == (const ProfileService_getData_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const ProfileService_getData_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProfileService_getData_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProfileService_getData_pargs {
 public:


  virtual ~ProfileService_getData_pargs() throw();
  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProfileService_getData_result__isset {
  _ProfileService_getData_result__isset() : success(false) {}
  bool success :1;
} _ProfileService_getData_result__isset;

class ProfileService_getData_result {
 public:

  ProfileService_getData_result(const ProfileService_getData_result&);
  ProfileService_getData_result& operator=(const ProfileService_getData_result&);
  ProfileService_getData_result() {
  }

  virtual ~ProfileService_getData_result() throw();
  GetResult success;

  _ProfileService_getData_result__isset __isset;

  void __set_success(const GetResult& val);

  bool operator == (const ProfileService_getData_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProfileService_getData_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProfileService_getData_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProfileService_getData_presult__isset {
  _ProfileService_getData_presult__isset() : success(false) {}
  bool success :1;
} _ProfileService_getData_presult__isset;

class ProfileService_getData_presult {
 public:


  virtual ~ProfileService_getData_presult() throw();
  GetResult* success;

  _ProfileService_getData_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProfileService_setData_args__isset {
  _ProfileService_setData_args__isset() : key(false), value(false) {}
  bool key :1;
  bool value :1;
} _ProfileService_setData_args__isset;

class ProfileService_setData_args {
 public:

  ProfileService_setData_args(const ProfileService_setData_args&);
  ProfileService_setData_args& operator=(const ProfileService_setData_args&);
  ProfileService_setData_args() : key(), value() {
  }

  virtual ~ProfileService_setData_args() throw();
  std::string key;
  std::string value;

  _ProfileService_setData_args__isset __isset;

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const ProfileService_setData_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const ProfileService_setData_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProfileService_setData_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProfileService_setData_pargs {
 public:


  virtual ~ProfileService_setData_pargs() throw();
  const std::string* key;
  const std::string* value;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProfileService_setData_result__isset {
  _ProfileService_setData_result__isset() : success(false) {}
  bool success :1;
} _ProfileService_setData_result__isset;

class ProfileService_setData_result {
 public:

  ProfileService_setData_result(const ProfileService_setData_result&);
  ProfileService_setData_result& operator=(const ProfileService_setData_result&);
  ProfileService_setData_result() : success(0) {
  }

  virtual ~ProfileService_setData_result() throw();
  bool success;

  _ProfileService_setData_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const ProfileService_setData_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProfileService_setData_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProfileService_setData_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProfileService_setData_presult__isset {
  _ProfileService_setData_presult__isset() : success(false) {}
  bool success :1;
} _ProfileService_setData_presult__isset;

class ProfileService_setData_presult {
 public:


  virtual ~ProfileService_setData_presult() throw();
  bool* success;

  _ProfileService_setData_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProfileService_removeData_args__isset {
  _ProfileService_removeData_args__isset() : key(false) {}
  bool key :1;
} _ProfileService_removeData_args__isset;

class ProfileService_removeData_args {
 public:

  ProfileService_removeData_args(const ProfileService_removeData_args&);
  ProfileService_removeData_args& operator=(const ProfileService_removeData_args&);
  ProfileService_removeData_args() : key() {
  }

  virtual ~ProfileService_removeData_args() throw();
  std::string key;

  _ProfileService_removeData_args__isset __isset;

  void __set_key(const std::string& val);

  bool operator == (const ProfileService_removeData_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const ProfileService_removeData_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProfileService_removeData_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProfileService_removeData_pargs {
 public:


  virtual ~ProfileService_removeData_pargs() throw();
  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProfileService_removeData_result__isset {
  _ProfileService_removeData_result__isset() : success(false) {}
  bool success :1;
} _ProfileService_removeData_result__isset;

class ProfileService_removeData_result {
 public:

  ProfileService_removeData_result(const ProfileService_removeData_result&);
  ProfileService_removeData_result& operator=(const ProfileService_removeData_result&);
  ProfileService_removeData_result() : success(0) {
  }

  virtual ~ProfileService_removeData_result() throw();
  bool success;

  _ProfileService_removeData_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const ProfileService_removeData_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProfileService_removeData_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProfileService_removeData_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProfileService_removeData_presult__isset {
  _ProfileService_removeData_presult__isset() : success(false) {}
  bool success :1;
} _ProfileService_removeData_presult__isset;

class ProfileService_removeData_presult {
 public:


  virtual ~ProfileService_removeData_presult() throw();
  bool* success;

  _ProfileService_removeData_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ProfileServiceClient : virtual public ProfileServiceIf {
 public:
  ProfileServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProfileServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getData(GetResult& _return, const std::string& key);
  void send_getData(const std::string& key);
  void recv_getData(GetResult& _return);
  bool setData(const std::string& key, const std::string& value);
  void send_setData(const std::string& key, const std::string& value);
  bool recv_setData();
  bool removeData(const std::string& key);
  void send_removeData(const std::string& key);
  bool recv_removeData();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProfileServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProfileServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProfileServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getData(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_setData(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_removeData(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProfileServiceProcessor(boost::shared_ptr<ProfileServiceIf> iface) :
    iface_(iface) {
    processMap_["getData"] = &ProfileServiceProcessor::process_getData;
    processMap_["setData"] = &ProfileServiceProcessor::process_setData;
    processMap_["removeData"] = &ProfileServiceProcessor::process_removeData;
  }

  virtual ~ProfileServiceProcessor() {}
};

class ProfileServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProfileServiceProcessorFactory(const ::boost::shared_ptr< ProfileServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProfileServiceIfFactory > handlerFactory_;
};

class ProfileServiceMultiface : virtual public ProfileServiceIf {
 public:
  ProfileServiceMultiface(std::vector<boost::shared_ptr<ProfileServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProfileServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProfileServiceIf> > ifaces_;
  ProfileServiceMultiface() {}
  void add(boost::shared_ptr<ProfileServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getData(GetResult& _return, const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getData(_return, key);
    }
    ifaces_[i]->getData(_return, key);
    return;
  }

  bool setData(const std::string& key, const std::string& value) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->setData(key, value);
    }
    return ifaces_[i]->setData(key, value);
  }

  bool removeData(const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->removeData(key);
    }
    return ifaces_[i]->removeData(key);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProfileServiceConcurrentClient : virtual public ProfileServiceIf {
 public:
  ProfileServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProfileServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getData(GetResult& _return, const std::string& key);
  int32_t send_getData(const std::string& key);
  void recv_getData(GetResult& _return, const int32_t seqid);
  bool setData(const std::string& key, const std::string& value);
  int32_t send_setData(const std::string& key, const std::string& value);
  bool recv_setData(const int32_t seqid);
  bool removeData(const std::string& key);
  int32_t send_removeData(const std::string& key);
  bool recv_removeData(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
