/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "profileservice_constants.h"

namespace profileservice {

const profileserviceConstants g_profileservice_constants;

profileserviceConstants::profileserviceConstants() {
}

} // namespace

