/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef profileservice_CONSTANTS_H
#define profileservice_CONSTANTS_H

#include "profileservice_types.h"

namespace profileservice {

class profileserviceConstants {
 public:
  profileserviceConstants();

};

extern const profileserviceConstants g_profileservice_constants;

} // namespace

#endif
